/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as IndexImport } from './routes/index'
import { Route as SettingsIndexImport } from './routes/settings/index'
import { Route as RuleManagerIndexImport } from './routes/ruleManager/index'
import { Route as NetworkIndexImport } from './routes/network/index'
import { Route as ApiDebugIndexImport } from './routes/apiDebug/index'
import { Route as SettingsNetworkImport } from './routes/settings/network'
import { Route as SettingsGeneralImport } from './routes/settings/general'
import { Route as SettingsClientProxyImport } from './routes/settings/client-proxy'
import { Route as SettingsCertificatesImport } from './routes/settings/certificates'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)

const RuleManagerIndexRoute = RuleManagerIndexImport.update({
  id: '/ruleManager/',
  path: '/ruleManager/',
  getParentRoute: () => rootRoute,
} as any)

const NetworkIndexRoute = NetworkIndexImport.update({
  id: '/network/',
  path: '/network/',
  getParentRoute: () => rootRoute,
} as any)

const ApiDebugIndexRoute = ApiDebugIndexImport.update({
  id: '/apiDebug/',
  path: '/apiDebug/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsNetworkRoute = SettingsNetworkImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => SettingsRoute,
} as any)

const SettingsGeneralRoute = SettingsGeneralImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)

const SettingsClientProxyRoute = SettingsClientProxyImport.update({
  id: '/client-proxy',
  path: '/client-proxy',
  getParentRoute: () => SettingsRoute,
} as any)

const SettingsCertificatesRoute = SettingsCertificatesImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => SettingsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/settings/certificates': {
      id: '/settings/certificates'
      path: '/certificates'
      fullPath: '/settings/certificates'
      preLoaderRoute: typeof SettingsCertificatesImport
      parentRoute: typeof SettingsImport
    }
    '/settings/client-proxy': {
      id: '/settings/client-proxy'
      path: '/client-proxy'
      fullPath: '/settings/client-proxy'
      preLoaderRoute: typeof SettingsClientProxyImport
      parentRoute: typeof SettingsImport
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralImport
      parentRoute: typeof SettingsImport
    }
    '/settings/network': {
      id: '/settings/network'
      path: '/network'
      fullPath: '/settings/network'
      preLoaderRoute: typeof SettingsNetworkImport
      parentRoute: typeof SettingsImport
    }
    '/apiDebug/': {
      id: '/apiDebug/'
      path: '/apiDebug'
      fullPath: '/apiDebug'
      preLoaderRoute: typeof ApiDebugIndexImport
      parentRoute: typeof rootRoute
    }
    '/network/': {
      id: '/network/'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkIndexImport
      parentRoute: typeof rootRoute
    }
    '/ruleManager/': {
      id: '/ruleManager/'
      path: '/ruleManager'
      fullPath: '/ruleManager'
      preLoaderRoute: typeof RuleManagerIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof SettingsImport
    }
  }
}

// Create and export the route tree

interface SettingsRouteChildren {
  SettingsCertificatesRoute: typeof SettingsCertificatesRoute
  SettingsClientProxyRoute: typeof SettingsClientProxyRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsNetworkRoute: typeof SettingsNetworkRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCertificatesRoute: SettingsCertificatesRoute,
  SettingsClientProxyRoute: SettingsClientProxyRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsNetworkRoute: SettingsNetworkRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/certificates': typeof SettingsCertificatesRoute
  '/settings/client-proxy': typeof SettingsClientProxyRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/apiDebug': typeof ApiDebugIndexRoute
  '/network': typeof NetworkIndexRoute
  '/ruleManager': typeof RuleManagerIndexRoute
  '/settings/': typeof SettingsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/certificates': typeof SettingsCertificatesRoute
  '/settings/client-proxy': typeof SettingsClientProxyRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/apiDebug': typeof ApiDebugIndexRoute
  '/network': typeof NetworkIndexRoute
  '/ruleManager': typeof RuleManagerIndexRoute
  '/settings': typeof SettingsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/certificates': typeof SettingsCertificatesRoute
  '/settings/client-proxy': typeof SettingsClientProxyRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/network': typeof SettingsNetworkRoute
  '/apiDebug/': typeof ApiDebugIndexRoute
  '/network/': typeof NetworkIndexRoute
  '/ruleManager/': typeof RuleManagerIndexRoute
  '/settings/': typeof SettingsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/certificates'
    | '/settings/client-proxy'
    | '/settings/general'
    | '/settings/network'
    | '/apiDebug'
    | '/network'
    | '/ruleManager'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/certificates'
    | '/settings/client-proxy'
    | '/settings/general'
    | '/settings/network'
    | '/apiDebug'
    | '/network'
    | '/ruleManager'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/settings/certificates'
    | '/settings/client-proxy'
    | '/settings/general'
    | '/settings/network'
    | '/apiDebug/'
    | '/network/'
    | '/ruleManager/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ApiDebugIndexRoute: typeof ApiDebugIndexRoute
  NetworkIndexRoute: typeof NetworkIndexRoute
  RuleManagerIndexRoute: typeof RuleManagerIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ApiDebugIndexRoute: ApiDebugIndexRoute,
  NetworkIndexRoute: NetworkIndexRoute,
  RuleManagerIndexRoute: RuleManagerIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/settings",
        "/apiDebug/",
        "/network/",
        "/ruleManager/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx",
      "children": [
        "/settings/certificates",
        "/settings/client-proxy",
        "/settings/general",
        "/settings/network",
        "/settings/"
      ]
    },
    "/settings/certificates": {
      "filePath": "settings/certificates.tsx",
      "parent": "/settings"
    },
    "/settings/client-proxy": {
      "filePath": "settings/client-proxy.tsx",
      "parent": "/settings"
    },
    "/settings/general": {
      "filePath": "settings/general.tsx",
      "parent": "/settings"
    },
    "/settings/network": {
      "filePath": "settings/network.tsx",
      "parent": "/settings"
    },
    "/apiDebug/": {
      "filePath": "apiDebug/index.tsx"
    },
    "/network/": {
      "filePath": "network/index.tsx"
    },
    "/ruleManager/": {
      "filePath": "ruleManager/index.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.tsx",
      "parent": "/settings"
    }
  }
}
ROUTE_MANIFEST_END */
