//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::app_config::Entity as AppConfig;
pub use super::request::Entity as Request;
pub use super::response::Entity as Response;
pub use super::rule::Entity as Rule;
pub use super::rule_group::Entity as RuleGroup;
