// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Expr = 2,
  OrExpr = 3,
  AndExpr = 4,
  NotExpr = 5,
  NotOp = 6,
  Primary = 7,
  Url = 8,
  Scheme = 9,
  Host = 10,
  Port = 11,
  Path = 12,
  AndOp = 15,
  OrOp = 16
