version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: lynx-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # HTTP collector
      - "14250:14250" # gRPC collector
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "6831:6831/udp" # UDP agent (Thrift compact)
      - "6832:6832/udp" # UDP agent (Thrift binary)
      - "5778:5778" # HTTP config
      - "5775:5775/udp" # UDP zipkin
      - "9411:9411" # Zipkin compatible endpoint
    command:
      - "--memory.max-traces=10000"
      - "--query.base-path=/jaeger/ui"
      - "--log-level=info"
      - "--query.max-clock-skew-adjustment=1s" 
    restart: unless-stopped
    networks:
      - jaeger-network

networks:
  jaeger-network:
    driver: bridge
