//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rule")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub r#match: String,
    pub target_uri: String,
    pub rule_group_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::rule_group::Entity",
        from = "Column::RuleGroupId",
        to = "super::rule_group::Column::Id"
    )]
    RuleGroup,
}

impl Related<super::rule_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RuleGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
