//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4


use once_cell::sync::OnceCell;
use sea_orm::{Database, DatabaseConnection};

use crate::config::AppConfig;

pub mod prelude;

pub mod rule;
pub mod rule_group;

pub const DB: OnceCell<DatabaseConnection> = OnceCell::new();

pub async fn set_up_db(app_config: &AppConfig) -> DatabaseConnection {
    let schema = format!(
        "sqlite://{}?mode=rwc",
        app_config.get_db_path().to_string_lossy()
    );
    
    Database::connect(schema)
        .await
        .expect("Failed to connect to db")
}
