//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::{Database, DatabaseConnection};
use sea_orm_migration::MigratorTrait;

use crate::{config::AppConfig, migration::Migrator};

pub mod prelude;

pub mod app_config;
pub mod request;
pub mod response;
pub mod rule;
pub mod rule_group;

pub async fn set_up_db(config: &AppConfig) -> DatabaseConnection {
    let schema = format!(
        "sqlite://{}?mode=rwc",
        config.get_db_path().to_string_lossy()
    );
    let db = Database::connect(schema)
        .await
        .expect("Failed to connect to db");
    #[cfg(feature = "test")]
    let _ = Migrator::refresh(&db).await;

    db
}
