//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use migration::MigratorTrait;
use once_cell::sync::OnceCell;
use sea_orm::{Database, DatabaseConnection};
use tracing::debug;

use crate::config::AppConfig;

pub mod prelude;

pub mod app_config;
pub mod rule;
pub mod rule_group;

pub const DB: OnceCell<DatabaseConnection> = OnceCell::new();

pub async fn set_up_db(app_config: &AppConfig) -> DatabaseConnection {
    let schema = format!(
        "sqlite://{}?mode=rwc",
        app_config.get_db_path().to_string_lossy()
    );
    debug!("Connect to db {schema}");

    let con = Database::connect(schema)
        .await
        .expect("Failed to connect to db");

    migration::Migrator::refresh(&con)
        .await
        .expect("Failed to migrate db");
    return con;
}
