//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::{Database, DatabaseConnection};
use sea_orm_migration::MigratorTrait;

use crate::migration::Migrator;

pub mod prelude;

pub mod app_config;
