// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordingStatus } from "./RecordingStatus";

export type Model = { id: number, recordingStatus: RecordingStatus, captureSSL: boolean, sslConfig: Record<string, string> | null, maxLogSize: number, clearLogSize: number, };
