// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureType } from "./CaptureType";

export type Model = { id: number, type: CaptureType, url: string, ruleId: number, };
