// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CaptureType } from "./CaptureType";

export type Capture = { type: CaptureType, url: string, };
