// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Model } from "./AppConfigModel";
import type { ResponseBox } from "./ResponseBox";

export type GetAppConfigResponse = ResponseBox<Model | null>;
