// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Model } from "./RequestModel";
import type { WebSocketLog } from "./WebSocketLog";

export type MessageLog = { "request": Model } | { "webSocket": WebSocketLog };
