// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Model = { id: number, uri: string, traceId: string, method: string, schema: string, version: string, statusCode: number | null, responseMimeType: string | null, header: Record<string, any> | null, headerSize: number | null, };
