// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capture } from "./Capture";
import type { Handler } from "./Handler";

export type RuleUpdateContentParams = { id: number, capture: Capture, handlers: Array<Handler>, };
