// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SendType } from "./SendType";

export type WebSocketLog = { traceId: string, sendType: SendType, data: string, };
